name: Validate Capabilities

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - 'capabilities/**/*.yaml'
      - 'capabilities/**/capability.yaml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema pyyaml
          
      - name: Run schema validation
        run: |
          python validators/validator.py --schema schema/enact-schema.json --capabilities capabilities
          
      - name: Check README files exist
        run: |
          find capabilities -type d -name '[A-Z]*' | while read dir; do
            if [ ! -f "$dir/README.md" ]; then
              echo "::error file=$dir::Missing README.md file in $dir"
              exit 1
            fi
          done